#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# set default editor
export EDITOR=vim
export VISUAL=vim

# set up gitignore
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

## pipenv
export PIPENV_VENV_IN_PROJECT=1
eval "$(pipenv --completion)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Google Cloud SDK.
if [ -f '/Users/joshpaulchan/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/joshpaulchan/google-cloud-sdk/path.zsh.inc'; fi

if [ -f '/Users/joshpaulchan/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/joshpaulchan/google-cloud-sdk/completion.zsh.inc'; fi

if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi

#### custom

# sends a specified JRPC command from a text file ($3) at a line number ($4) to port ($2) over host ($1)
# function topspin() {
# 	# echo "using $3"
# 	command="$(head -n $4 $3 | tail -n 1)"
# 	# echo "sending ${command}"
# 	result="$(echo $command | nc $1 $2)";
# 	echo "${result}" | json_pp 
# }
